### PR TITLE
Publish page or save page as draft

### PR DESCRIPTION
**Pull request by haydarai**

### CODE REVIEW

**Comment by yezarela** [comment]
@haydarai can't we customize the page slug?

**Comment by haydarai** [comment]
@yezarela yes we can, I forgot to handle that in backend. I will edit it tomorrow.

**Comment by haydarai** [comment]
@yezarela please recheck it if you have the time 😄

**Comment by yezarela** [comment]
@haydarai, mongo will throw error if i use duplicate page slug :D

**Comment by haydarai** [comment]
@yezarela fixed!

**Review by yezarela — APPROVED** [review]
Great

**Pull request merged**
