### PR TITLE
Upload capabilities for Site Logo, Site Cover, and Site Favicon

### PR DESCRIPTION
**Pull request by haydarai**
Also shows preview of saved images in `admin/general` page.

### CODE REVIEW

**Comment by yezarela** [comment]
@haydarai How about file restriction? don't we need to restrict only image files?

**Comment by haydarai** [comment]
@yezarela yeah I think we should. I will modify it tomorrow.

**Comment by haydarai** [comment]
@yezarela done, please kindly recheck

**Review by yezarela — APPROVED** [review]
LGTM

**Pull request merged**
