### PR TITLE
CRUD Navigation

### PR DESCRIPTION
**Pull request by yezarela**
This PR creates these endpoints:

- `POST /sites/:id/navigations`, create/update navigations.
- `GET /sites/:id/navigations`, get navigations.
- `DEL /sites/:id/navigations/:navigationId`, delete navigation.

Postman collection https://www.getpostman.com/collections/1922ba1b3b68dee61f5e

### CODE REVIEW

**Comment by haydarai** [comment]
@yezarela it's still possible to make multiple navigation with duplicated order, is it difficult to handle that? If it's difficult then I think we can skip that.

**Comment by yezarela** [comment]
@haydarai ok, I'll fix that later tonight

**Comment by yezarela** [comment]
@haydarai updated, Please kindly recheck :)

**Comment by haydarai** [comment]
Not solved yet, here is a way to reproduce:
1. POST `localhost:8080/sites/5a0b2851ef0592283e89ec64/navigations`
```
{
  "navigations": [
    {
      "url": "http://localhost:8000/home",
      "label": "Home",
      "order": 1
    }
  ]
}
```
2. POST `localhost:8080/sites/5a0b2851ef0592283e89ec64/navigations`
```
{
  "navigations": [
    {
      "url": "http://localhost:8000/about",
      "label": "About",
      "order": 1
    }
  ]
}
```
3. Both of `home` and `about` will have same `order === 1`

**Comment by yezarela** [comment]
@haydarai it's not intended to update navigation one by one according to the UI, should we make it possible?

**Comment by haydarai** [comment]
After a second thought, it might be over-engineering. Let's merge this one.

**Review by haydarai — APPROVED** [review]

**Pull request merged**
